### ISSUE TITLE
Can't add phone numbers to Philia Contacts

### ISSUE THREAD

**Issue by bogerard** [aaron-salisbury/PhiliaContacts#1]
Import went fine, but the program doesn't let me add phone numbers to existing contacts

**Comment by aaron-salisbury** [comment]
Thank you for the feedback.

I concede that it may not be the best UX or control, but did you notice the little + symbol next to the label?

![AddingNewContactNumber](https://user-images.githubusercontent.com/21088184/187302043-5db060f6-11da-40f6-b701-9ddd0ef9b088.gif)

**Comment by aaron-salisbury** [comment]
Closing as I am not able to recreate the issue. If it happens again, please let me know. Thank you.
